spring:
  application:
    name: board-auth

  datasource:
    # MySQL 접속 주소
    url: jdbc:log4jdbc:mysql://localhost:3306/board_auth
    # DB 접속 계정
    username: root
    # DB 비밀번호
    password: green502
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

mybatis:
  # MyBatis Mapper XML 파일 위치
    configuration:
      # DB 컬럼명과 자바 필드명 자동 매핑 설정
      # ex) created_at → createdAt
      map-underscore-to-camel-case: true
    mapper-locations: mappers/**/*.xml
